### PR TITLE
add Visium Spatial transcriptomics voila dashboard

### PR DESCRIPTION
**Pull request by cornhundred**
This example show how we can interactively explore high-dimensional and spatial transcriptomics data produced by the Visium assay from 10X Genomics. We are using Bqplot to display the spatial data and the interactive heatmap Clustergrammer2 to display the high-dimensional gene expression data. The views are linked and enable users to overlay gene expression or unbiased clustering results on the spatial view. We also allow transition to UMAP projection of data.

The GIF we're using is 1.53MB large. We can lower the size if needed.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

The current gallery is already pulling ~20MB:

image

One of the largest files is the gif for the GPX viewer example (~9MB), which I'm planning to replace by a static image instead.

Maybe we could also use a screenshot instead of screencast? Otherwise I think 1.53MB sounds still acceptable for now.

What do you think?

**Comment by jtpio** [comment]
In the end it would be great for the landing page of the gallery to pull less than 20MB of content, especially if some users browse it on their phones using mobile data.

**Comment by cornhundred** [comment]
Hi @jtpio, I switched to using a small GIF at 297KB. Let me know if that works :)

**Comment by jtpio** [comment]
Perfect, thanks @cornhundred!

And thanks for adding a new example!

**Comment by cornhundred** [comment]
Thank you for hosting!!

**Pull request merged**
